### ISSUE TITLE
[Fix] modify how the "wide" format table is output

### ISSUE THREAD

**Issue by sjchiass** [AlexCornish/SideProjects1#3]
Currently the wide format has headers like these:

```
series_id,footnote_codes,"('value', '1994-01-01')","('value', '1994-02-01')","('value', '1994-03-01')","('value', '1994-04-01')", ...
```

but they should be like these

```
series_id,footnote_codes,value_1994-01-01,value_1994-02-01,value_1994-03-01,value_1994-04-01, ...
```

**Comment by AlexCornish** [comment]
![image](https://user-images.githubusercontent.com/64739094/90282917-30200e80-de3d-11ea-8caf-e03e8cc1358b.png)
![image](https://user-images.githubusercontent.com/64739094/90282977-53e35480-de3d-11ea-9ebe-3a74f7e6f4a6.png)

**Comment by sjchiass** [comment]
:+1:
