### ISSUE TITLE
[Fix] quarters should be identified in one column

### ISSUE THREAD

**Issue by sjchiass** [AlexCornish/SideProjects1#4]
Currently quarters are identified in two columns: year and quarter (if I remember correctly). They should be written as yyyyQq instead, such as 2020Q3. They can then belong to a single column called `reference_period`.

Months and years should also be in a `reference_period` column. The user can determine the frequency of the data by looking at the values.

**Comment by AlexCornish** [comment]
![image](https://user-images.githubusercontent.com/64739094/90275277-03192f00-de30-11ea-88a7-77fb73afe095.png)
Changes made to change the individual years and quarters into a single reference period column.

**Comment by sjchiass** [comment]
I tested yearly averages for industries but did not get the `reference_period` column.

edit: Same for commodities.
