### ISSUE TITLE
[Fix] more verbose data download indicator

### ISSUE THREAD

**Issue by sjchiass** [AlexCornish/SideProjects1#6]
Currently the script indicates whether no new data is available. It should also give information on versions, such as
```
No new data available (current version: 2020-08-11)
```
or
```
Downloading new data (previous version: 2020-07-14; new version: 2020-08-11)
```
This way the user can have an idea of what the data is up to.

**Comment by AlexCornish** [comment]
![img1](https://user-images.githubusercontent.com/64739094/90268217-aebc8200-de24-11ea-8517-31a34b26a7a5.png)
- The text that indicates that the latest version is downloading. 
![img2](https://user-images.githubusercontent.com/64739094/90268312-d3b0f500-de24-11ea-8539-e29ebaa9a6ec.png)
- The text that indicates the latest version is already downloaded.

**Comment by sjchiass** [comment]
Tested and validated.

**Comment by sjchiass** [comment]
I tried this with industry but did not get the message.

**Comment by AlexCornish** [comment]
Fixed the issue. Turns out that the function hadn't been modified to display the new download indicator, if there was no previous copy of the data.
